version: '3'
services:

  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./rails/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      TZ:   UTC # os
      PGTZ: UTC # postgres
    restart: always

  # Backend
  rails:
    restart: always
    build:
      context: ./rails
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$NUXT_PORT"
    volumes:
      - "./rails:/$WORKDIR"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "$RAILS_PORT:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  # Frontend
  nuxt:
    restart: always
    build:
      context: ./nuxt
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$RAILS_PORT"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command: yarn run dev
    volumes:
      - "./nuxt:/$WORKDIR"
    ports:
      - "$NUXT_PORT:3000"
    # depends_on:
    #   - rails
    stdin_open: true
    tty: true
