version: '3'
services:

  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - ./rails/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always

  rails:
    restart: always
    build:
      context: ./rails
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./rails/:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    stdin_open: true
    tty: true
