version: '3'
services:

  # MySQL
  # mysql:
  #   restart: always
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     TZ: Asia/Tokyo
  #   ports:
  #     - '3306:3306'
  #   command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #     - ./tmp/mysql:/var/lib/mysql
  #     - ./my.cnf:/etc/mysql/conf.d/my.cnf
  #   tty: true

  # PostgreSQL
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin-pass'
    restart: always

  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    stdin_open: true
    tty: true
